version: "3.8"

services:
  dev:
    image: timpietyper:dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - "5173:5173"

  test:
    image: timpietyper:test
    build:
      context: .
      target: testing
    command: npm test
