services:
  prod:
    image: timpietyper
    container_name: timpietyper
    build:
      context: .
      target: production
    ports:
      - "5183:80"
    environment:
      - NODE_ENV=production
    networks:
      - timpietyper_default

networks:
  timpietyper_default:
    external: true