services:
  dev:
    image: timpietyper-dev
    container_name: timpietyper-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - "5173:5173"

  test:
    image: timpietyper-test
    container_name: timpietyper-test
    build:
      context: .
      target: testing
    command: npm test
