services:
  dev:
    image: timpietyper-dev
    container_name: timpietyper
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - "5173:5173"
    networks:
      - timpietyper_default

  test:
    image: timpietyper-test
    container_name: timpietyper-test
    build:
      context: .
      target: testing
    command: npm test
    networks:
      - timpietyper_default

networks:
  timpietyper_default:
    external: true