name: Deploying

on:
  push:
    branches: 
      - main
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Deploy
        run: make prod