name: Testing

on:
  push:
  workflow_dispatch:
  
jobs:
  test:
      runs-on: self-hosted
      steps:
        - name: checkout repository
          uses: actions/checkout@v3

        - name: unit tests
          run: make test